### ISSUE TITLE
Not working on UI 4.0

### ISSUE THREAD

**Issue by Karish0711** [SamSprung/SamSprung-Launcher#1]
Hi
Plsss make this available for UI 4.0

**Comment by chopped0815** [comment]
Yes please that is my dream. I love it

**Comment by AbandonedCart** [comment]
It's exclusively tested on Android 12.

**Comment by Karish0711** [comment]
Please tell me a way to access the widget.and if its tested when is it
expexted to launch???

**Comment by AbandonedCart** [comment]
Follow the directions in the README. It's the stuff below the files at https://github.com/SamSprung/SamSprung-Launcher

I don't know what you mean by launch. It launched. You're here.

**Comment by Karish0711** [comment]
Hiiieee

I am using the flip 3. I want to acess the samsprung widget
But I accidently updated to one ui 4 and android 12

I am unable to use the samsprung widget now. I really want to use it.

**Comment by AbandonedCart** [comment]
You're in the right place.

**Comment by Karish0711** [comment]
Can you please help me with it??

**Comment by AbandonedCart** [comment]
Help you with what?

**Comment by Karish0711** [comment]
The samsprung widget is not working on android 12
So i need help regarding this issue

**Comment by AbandonedCart** [comment]
That is why you are here, not there.

**Comment by Karish0711** [comment]
Umm Didnt get you
Yes i m here to know if there is any alternative

**Comment by AbandonedCart** [comment]
This is it.

**Comment by Karish0711** [comment]
You mean there is nothing I can do to get the samsprunger widget working in
android 12?

**Comment by AbandonedCart** [comment]
That is why we are here.

**Comment by Karish0711** [comment]
Okay.
Please give the users another big update where samsprung can be used in one
ui 4

**Comment by AbandonedCart** [comment]
Done.

**Comment by AbandonedCart** [comment]
![image](https://user-images.githubusercontent.com/1173913/150074128-c1204ad9-0dc0-4e77-8af0-66033b8973d6.png)
