### ISSUE TITLE
Auto Rotation Setting

### ISSUE THREAD

**Issue by armaustin** [SamSprung/SamSprung-Launcher#11]
This app is constantly enabling my phone's Auto Screen Rotation setting.  Every time I lock my phone, this app turns on the auto rotate. How do I disable this from happening? I want to use this amazing app but that setting is driving me crazy...

**Comment by AbandonedCart** [comment]
It should only be enabling automatic rotation if it was already enabled.

**Comment by armaustin** [comment]
Well, I keep turning it off (from the quick access toolbar at top of screen) every time I flip open my phone. Once I close the phone and open it again, the setting is turned on. every single time.  Now if I take away the apps Write to system settings privilege, this does not happen. However the app of course won't function correctly that way.

**Comment by AbandonedCart** [comment]
Did you update to 68be315?

**Comment by armaustin** [comment]
Yes I just updated to the latest version released 8 minutes ago. It still auto enables the rotate setting every time I close the phone and open it.

**Comment by AbandonedCart** [comment]
For some reason, it is not storing your existing setting

**Comment by armaustin** [comment]
I will try deleting the app and redownloading

**Comment by armaustin** [comment]
Deleting and reinstalling seemed to fix it. It is keeping the setting now.  Thanks for this great app!
