### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Albo1990** [SamSprung/SamSprung-Launcher#4]
Se vado si impostazioni- schermo esterno- widget, poi però non mi appare samsprung launcher e di conseguenza non funziona.. perché? Ho autorizzato tutto eppure non va

**Comment by AbandonedCart** [comment]
English, please. I have not installed Google Translate.

**Comment by Albo1990** [comment]
if I go to settings-external screen-widget, then samsprung launcher
does not appear, why? I have installed and authorized everything, yet
it does not work ..


Il Ven 21 Gen 2022, 02:26 TwistedUmbrellaX ***@***.***> ha
scritto:

**Comment by AbandonedCart** [comment]
That was the widget. This doesn't need to be added.

**Comment by Albo1990** [comment]
but it doesn't work the same ... everything appears on the external
screen, all the apps, but if I press on one of them nothing opens and
I am left with a black screen with only the words samsprung


Il Ven 21 Gen 2022, 02:41 TwistedUmbrellaX ***@***.***> ha
scritto:

**Comment by AbandonedCart** [comment]
Do you have a secure lock screen (password, fingerprint) without using bixby unlock? Per the directions, you need to use swipe, none, or configure bixby unlock to handle a lock screen.

If it still fails, use the report issue option in the app and it will record a log of the issue.
